In [1]:
import datetime
import pandas as pd
from pandas import DataFrame
from pprint import pprint
import json
import xlsxwriter
import numpy as np
import pandas.io.sql as psql
import mysql.connector


mydb = mysql.connector.connect(
  host="prod-babymd-mysql-rds-01.cyw98bspufl6.ap-south-1.rds.amazonaws.com",
  user="monodeep.saha",
  password="80w70Zl5F7guX7",
  database="babymd_production"
)
mycursor = mydb.cursor()
conn = mycursor.execute

sql_query = """
SELECT * 
FROM babymd_production.user_crm_lead ucl 
LEFT JOIN babymd_production.webhook_wati_message_status wwms 
ON ucl.whatsapp_mobile_number = wwms.wa_id
WHERE ucl.lead_created_time IS NOT NULL;
"""
df_DATA = pd.read_sql_query(sql_query,mydb)
df_DATA
df_DATA['DATE']= df_DATA["lead_created_time"].dt.date
df_DATA['Month']= df_DATA["lead_created_time"].dt.month

df_DATA

C:\Users\Admin\AppData\Local\Temp\ipykernel_4228\3908914112.py:28: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_DATA = pd.read_sql_query(sql_query,mydb)

,id,owner,modified_by,created_by,baby_birth_weight,baby_dob,dob,lead_category,street,lead_id,...,source_url,avatar_url,operator_name,message_contact,sender_name,list_reply,reply_context_id,raw_data,DATE,Month
0,188,"{""id"": ""566277000000284001"", ""name"": ""deeksha""...","{""id"": ""566277000000284001"", ""name"": ""deeksha""...","{""id"": ""566277000000284001"", ""name"": ""deeksha""...",,2023-04-24,,Post Trial,,566277000003852515,...,None,None,None,None,None,None,None,None,2024-01-17,1
1,233,"{""id"": ""566277000000284001"", ""name"": ""deeksha""...","{""id"": ""566277000000284001"", ""name"": ""deeksha""...","{""id"": ""566277000000284001"", ""name"": ""deeksha""...",,2022-03-15,,Post Trial,,566277000003809426,...,None,None,None,None,None,None,None,None,2024-01-15,1
2,299,"{""id"": ""566277000000284001"", ""name"": ""deeksha""...","{""id"": ""566277000000284001"", ""name"": ""deeksha""...","{""id"": ""566277000000284001"", ""name"": ""deeksha""...",,2023-10-23,,Post-Trial,,566277000003742194,...,None,None,None,None,None,None,None,None,2024-01-12,1
3,325,"{""id"": ""566277000000284001"", ""name"": ""deeksha""...","{""id"": ""566277000000284001"", ""name"": ""deeksha""...","{""id"": ""566277000000284001"", ""name"": ""deeksha""...",,2023-08-11,,Post-Trial,,566277000003689062,...,None,None,None,None,None,None,None,None,2024-01-12,1
4,570,"{""id"": ""566277000000284001"", ""name"": ""deeksha""...","{""id"": ""566277000000284001"", ""name"": ""deeksha""...","{""id"": ""566277000000284001"", ""name"": ""deeksha""...",,2023-12-16,,Post Trial,,566277000003251148,...,None,None,None,None,None,None,None,None,2024-01-05,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16640,1071,"{""id"": ""566277000000284001"", ""name"": ""deeksha""...","{""id"": ""566277000000284001"", ""name"": ""deeksha""...","{""id"": ""566277000000284001"", ""name"": ""deeksha""...",,2023-06-19,,New,,566277000002193432,...,None,None,None,None,None,None,None,None,2023-12-14,12
16641,1090,"{""id"": ""566277000000284001"", ""name"": ""deeksha""...","{""id"": ""566277000000284001"", ""name"": ""deeksha""...","{""id"": ""566277000000284001"", ""name"": ""deeksha""...",,2023-11-10,,Post Trial,,566277000002179266,...,None,None,None,None,None,None,None,None,2023-12-14,12
16642,1106,"{""id"": ""566277000000284001"", ""name"": ""deeksha""...","{""id"": ""566277000000284001"", ""name"": ""deeksha""...","{""id"": ""566277000000284001"", ""name"": ""deeksha""...",,2019-09-07,,Post Trial,,566277000002170587,...,None,None,None,None,None,None,None,None,2023-12-16,12
16643,1649,"{""id"": ""566277000000284001"", ""name"": ""deeksha""...","{""id"": ""566277000000284001"", ""name"": ""deeksha""...","{""id"": ""566277000000284001"", ""name"": ""deeksha""...",,2023-05-14,,Junk,,566277000000866004,...,None,None,None,None,None,None,None,None,2023-11-07,11
16644,1681,"{""id"": ""566277000000284001"", ""name"": ""deeksha""...","{""id"": ""566277000000284001"", ""name"": ""deeksha""...","{""id"": ""566277000000284001"", ""name"": ""deeksha""...",,2023-05-14,,Junk,,566277000000866004,...,None,None,None,None,None,None,None,None,2023-11-07,11

In [2]:
df_Final = df_DATA [["baby_dob", "lead_category", "lead_id", "created_time", "parent_relation", "last_chat", "feedback_notes", "current_medicine", "in_clinic_category", "full_name", "lead_status", "lead_type", "form_location", "utm_ad_name", "lead_created_time", "previous_history_of_admission", "mobile", "lead_source", "baby_age_month", "email", "keywords", "baby_gender", "last_activity_time", "utm_campaign", "whatsapp_mobile_number", "baby_feeding_method", "baby_any_current_medication", "utm_adset_name", "preconsult_information", "lead_sub_status", "modified_time", "lead_sub_source", "previous_allergies", "feedback_type", "last_name", "consultation_247_chat", "id", "id", "updated_at", "event_type", "local_message_id", "wati_id", "whatsapp_message_id", "template_id", "template_name", "created_at", "conversation_id", "ticket_id", "message_text", "operator_email", "wa_id", "message_type", "status_string", "source_type", "message_timestamp", "assignee_id", "data", "operator_name", "sender_name","DATE","Month"]]
df_Final

,baby_dob,lead_category,lead_id,created_time,parent_relation,last_chat,feedback_notes,current_medicine,in_clinic_category,full_name,...,message_type,status_string,source_type,message_timestamp,assignee_id,data,operator_name,sender_name,DATE,Month
0,2023-04-24,Post Trial,566277000003852515,2024-01-17 12:28:32,Father,247 chat,,,,Vishal Bhatt,...,None,None,None,None,None,None,None,None,2024-01-17,1
1,2022-03-15,Post Trial,566277000003809426,2024-01-15 07:00:56,Mother,Nutri chat,,Calcimax and rocaltrol@0.25mg,,Natasha Sagar,...,None,None,None,None,None,None,None,None,2024-01-15,1
2,2023-10-23,Post-Trial,566277000003742194,2024-01-12 13:55:37,Mother,247 chat,,Not taking medicine but she diagnosed with neo...,,Shweta,...,None,None,None,None,None,None,None,None,2024-01-12,1
3,2023-08-11,Post-Trial,566277000003689062,2024-01-12 08:46:03,,,,,,Pinaki,...,None,None,None,None,None,None,None,None,2024-01-12,1
4,2023-12-16,Post Trial,566277000003251148,2024-01-05 12:58:14,,247 chat,,,,Minaxi Minaxi,...,None,None,None,None,None,None,None,None,2024-01-05,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16640,2023-06-19,New,566277000002193432,2023-12-14 09:47:36,,,,,,Jyoti Santosh,...,None,None,None,None,None,None,None,None,2023-12-14,12
16641,2023-11-10,Post Trial,566277000002179266,2023-12-14 12:23:57,Mother,247 chat,,"Calcium, vitamin D3 and multi vitamin",,Baby of durgesh Nandini,...,None,None,None,None,None,None,None,None,2023-12-14,12
16642,2019-09-07,Post Trial,566277000002170587,2023-12-16 07:57:31,Father,247 chat,,,,Yuvansh Sharma,...,None,None,None,None,None,None,None,None,2023-12-16,12
16643,2023-05-14,Junk,566277000000866004,2023-11-07 11:47:39,,,,,,gau tests,...,None,None,None,None,None,None,None,None,2023-11-07,11
16644,2023-05-14,Junk,566277000000866004,2023-11-07 11:47:39,,,,,,gau tests,...,None,None,None,None,None,None,None,None,2023-11-07,11

In [7]:
pip install xlsxwriter

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: xlsxwriter in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (3.2.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
df_Final.to_csv('BABY_MD.csv',index = False)
df_Final

,baby_dob,lead_category,lead_id,created_time,parent_relation,last_chat,feedback_notes,current_medicine,in_clinic_category,full_name,...,message_type,status_string,source_type,message_timestamp,assignee_id,data,operator_name,sender_name,DATE,Month
0,2023-04-24,Post Trial,566277000003852515,2024-01-17 12:28:32,Father,247 chat,,,,Vishal Bhatt,...,None,None,None,None,None,None,None,None,2024-01-17,1
1,2022-03-15,Post Trial,566277000003809426,2024-01-15 07:00:56,Mother,Nutri chat,,Calcimax and rocaltrol@0.25mg,,Natasha Sagar,...,None,None,None,None,None,None,None,None,2024-01-15,1
2,2023-10-23,Post-Trial,566277000003742194,2024-01-12 13:55:37,Mother,247 chat,,Not taking medicine but she diagnosed with neo...,,Shweta,...,None,None,None,None,None,None,None,None,2024-01-12,1
3,2023-08-11,Post-Trial,566277000003689062,2024-01-12 08:46:03,,,,,,Pinaki,...,None,None,None,None,None,None,None,None,2024-01-12,1
4,2023-12-16,Post Trial,566277000003251148,2024-01-05 12:58:14,,247 chat,,,,Minaxi Minaxi,...,None,None,None,None,None,None,None,None,2024-01-05,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16640,2023-06-19,New,566277000002193432,2023-12-14 09:47:36,,,,,,Jyoti Santosh,...,None,None,None,None,None,None,None,None,2023-12-14,12
16641,2023-11-10,Post Trial,566277000002179266,2023-12-14 12:23:57,Mother,247 chat,,"Calcium, vitamin D3 and multi vitamin",,Baby of durgesh Nandini,...,None,None,None,None,None,None,None,None,2023-12-14,12
16642,2019-09-07,Post Trial,566277000002170587,2023-12-16 07:57:31,Father,247 chat,,,,Yuvansh Sharma,...,None,None,None,None,None,None,None,None,2023-12-16,12
16643,2023-05-14,Junk,566277000000866004,2023-11-07 11:47:39,,,,,,gau tests,...,None,None,None,None,None,None,None,None,2023-11-07,11
16644,2023-05-14,Junk,566277000000866004,2023-11-07 11:47:39,,,,,,gau tests,...,None,None,None,None,None,None,None,None,2023-11-07,11

In [4]:
import gspread
import csv
from oauth2client.service_account import ServiceAccountCredentials

# Define the OAuth2 scope
scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']

# Load the credentials from the JSON key file
credentials = ServiceAccountCredentials.from_json_keyfile_name('my-project-2024-414004-60efb95f9e7f.json', scope)

# Authorize the client using the credentials
gc = gspread.authorize(credentials)

# Open the spreadsheet by its ID
spreadsheetId = '17JJR02aOYnBPwIS6vAxCFF8PXta7mzXAWjsFJLbQhQE'
sh = gc.open_by_key(spreadsheetId)

# Define the sheet name and CSV file path
sheetName = 'RAW'
csvFile = 'BABY_MD.csv'

# Clear existing values in the specified range
sh.values_clear("'RAW'!A:BM")

# Read the CSV file with UTF-8 encoding and update the spreadsheet with its values
with open(csvFile, 'r', encoding='utf-8') as file:
    csv_values = list(csv.reader(file))
    sh.values_update(
        sheetName,
        params={'valueInputOption': 'USER_ENTERED'},
        body={'values': csv_values}
    )

# Print the data written
print("Data written to the spreadsheet:")
# for row in csv_values:
#     print(row)

# Print the number of rows and columns written
num_rows = len(csv_values)
num_columns = len(csv_values[0]) if csv_values else 0
print(f"Number of rows written: {num_rows}")
print(f"Number of columns written: {num_columns}")

Data written to the spreadsheet:
Number of rows written: 16646
Number of columns written: 63